from reviewer.models import ReviewResult


AI_REVIEW_MARKER = "<!-- ai-code-review-assistant -->"


def format_review_markdown(result: ReviewResult) -> str:
    """
    将 ReviewResult 转换成 GitHub PR Comment 使用的 Markdown。

    AI_REVIEW_MARKER 用于识别 AI Reviewer 自己创建的评论，
    从而在后续 Review 中更新已有评论，而不是重复创建。
    """

    lines = []

    # -------------------------------------------------
    # AI Review 唯一标识
    # -------------------------------------------------

    lines.append(AI_REVIEW_MARKER)
    lines.append("")

    lines.append("## 🤖 AI Code Review")
    lines.append("")

    # -------------------------------------------------
    # 没有发现问题
    # -------------------------------------------------

    if not result.issues:

        lines.append("### ✅ No issues found")
        lines.append("")

        lines.append(
            "AI Reviewer did not find any issues in this change."
        )

        lines.append("")

        lines.append(
            "_Generated by AI Code Review Assistant_"
        )

        return "\n".join(lines)

    # -------------------------------------------------
    # 问题数量
    # -------------------------------------------------

    lines.append(
        f"Found **{len(result.issues)} issue(s)**."
    )

    lines.append("")

    # -------------------------------------------------
    # 遍历所有问题
    # -------------------------------------------------

    for index, issue in enumerate(
        result.issues,
        start=1
    ):

        lines.append(
            f"### {index}. {issue.severity.upper()}"
        )

        lines.append("")

        # 文件

        if issue.file:

            lines.append(
                f"**File:** `{issue.file}`"
            )

        # 行号

        if issue.line:

            lines.append(
                f"**Line:** `{issue.line}`"
            )

        # 分类

        if issue.category:

            lines.append(
                f"**Category:** `{issue.category}`"
            )

        lines.append("")

        # 问题描述

        lines.append("**Problem**")
        lines.append("")

        lines.append(
            issue.message
        )

        lines.append("")

        # 修改建议

        lines.append("**Suggestion**")
        lines.append("")

        lines.append(
            issue.suggestion
        )

        lines.append("")

        # 代码片段

        if issue.code_snippet:

            lines.append("**Code**")
            lines.append("")

            lines.append("```java")

            lines.append(
                issue.code_snippet
            )

            lines.append("```")

            lines.append("")

        lines.append("---")
        lines.append("")

    # -------------------------------------------------
    # Footer
    # -------------------------------------------------

    lines.append(
        "_Generated by AI Code Review Assistant_"
    )

    return "\n".join(lines)