name: AI Code Review


on:

  pull_request:

    types:
      - opened
      - synchronize
      - reopened


permissions:

  contents: read

  pull-requests: write


jobs:


  review:


    runs-on: ubuntu-latest


    steps:


      -
        name: Checkout code

        uses: actions/checkout@v4

        with:

          fetch-depth: 0


      -
        name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"


      -
        name: Install dependencies

        run: |

          pip install -r requirements.txt


      -
        name: Run AI Review and Comment

        env:

          OPENAI_API_KEY:
            ${{ secrets.CR_API_KEY }}

          OPENAI_BASE_URL:
            ${{ secrets.CR_BASE_URL }}

          LLM_MODEL:
            ${{ secrets.CR_MODEL }}

          GITHUB_BASE_SHA:
            ${{ github.event.pull_request.base.sha }}

          GITHUB_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}


        run: |

          python main.py pr-comment \
            "${{ github.repository }}" \
            "${{ github.event.pull_request.number }}"